DROP TABLE IF EXISTS orderdetails;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS payments;

DROP TABLE IF EXISTS customers;

DROP TABLE IF EXISTS employees;

DROP TABLE IF EXISTS offices;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS productlines;


